import { IconProps as IP } from "react-bootstrap-icons";
import {
  ArrowBarLeft,
  ArrowBarRight,
  Basket,
  Building,
  Calendar2Check,
  Calendar2Month,
  Calendar2Range,
  CalendarWeek,
  Camera,
  CashStack,
  CheckCircleFill,
  CheckSquare,
  ChevronDown,
  Coin,
  Dash,
  DashCircleFill,
  Download,
  EmojiSunglasses,
  EnvelopeFill,
  EnvelopeOpen,
  ExclamationCircleFill,
  EyeFill,
  FileEarmarkEasel,
  FileEarmarkImage,
  FileEarmarkPlus,
  FileEarmarkSpreadsheet,
  FileEarmarkText,
  FileSpreadsheet,
  Files,
  FileText,
  FuelPump,
  GraphUp,
  Headphones,
  HouseDoor,
  Houses,
  Journals,
  Keyboard,
  ListCheck,
  ListStars,
  Lock,
  Newspaper,
  People,
  PeopleFill,
  PersonBadge,
  PersonCheck,
  PersonFillX,
  PersonLinesFill,
  PersonPlus,
  PlusCircleFill,
  Printer,
  PrinterFill,
  QuestionCircleFill,
  Send,
  Speaker,
  Toggles,
  Trash,
  UniversalAccess,
  Unlock,
  Upload,
  Wallet2,
} from "react-bootstrap-icons";

export const icons = {
  ArrowBarLeft,
  ArrowBarRight,
  Basket,
  Building,
  Calendar2Check,
  Calendar2Month,
  Calendar2Range,
  CalendarWeek,
  Camera,
  CashStack,
  CheckCircleFill,
  CheckSquare,
  ChevronDown,
  Coin,
  Dash,
  DashCircleFill,
  Download,
  EmojiSunglasses,
  EnvelopeFill,
  EnvelopeOpen,
  ExclamationCircleFill,
  EyeFill,
  FileEarmarkEasel,
  FileEarmarkImage,
  FileEarmarkPlus,
  FileEarmarkSpreadsheet,
  FileEarmarkText,
  FileSpreadsheet,
  Files,
  FileText,
  FuelPump,
  GraphUp,
  Headphones,
  HouseDoor,
  Houses,
  Journals,
  Keyboard,
  ListCheck,
  ListStars,
  Lock,
  Newspaper,
  People,
  PeopleFill,
  PersonBadge,
  PersonCheck,
  PersonFillX,
  PersonLinesFill,
  PersonPlus,
  PlusCircleFill,
  Printer,
  PrinterFill,
  QuestionCircleFill,
  Send,
  Speaker,
  Toggles,
  Trash,
  UniversalAccess,
  Unlock,
  Upload,
  Wallet2,
};
export interface IconProps extends IP {
  // Cannot use "name" as it is a valid SVG attribute
  // "iconName", "filename", "icon" will do it instead
  iconName: keyof typeof icons;
  size?: string | number;
}

export const IconForSmallBlock = ({ iconName, size, ...props }: IconProps) => {
  const BootstrapIcon = icons[iconName];
  return <BootstrapIcon size={size || 16} style={{ marginBottom: "-2px" }} {...props} />;
};
