// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   ../../../../../@fullcalendar/core

declare module "@fullcalendar/vue" {}

declare module "@fullcalendar/core/locales/de" {}
